Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,18 +10,23 @@ jobs:
 
     steps:
       - name: Print Docker Compose Version
-        run: docker compose version
-
-      - name: Checkout Code and Deploy App
         run: |
-          cd /home/docker/nextjs-express
+          docker-compose --version || docker compose version
 
-          git reset --hard
-          git clean -fd
-          git fetch origin
+      - name: Navigate and Deploy App
+        run: |
+          cd /home/ubuntu/nextjs-express
+
+          # Pull the latest changes from main
+          git stash || true
           git checkout main
           git pull origin main
 
-          docker compose up -d --build
+          # Build and run the Docker containers
+          docker-compose up -d --build
+
+          # Clean up unused Docker images
           docker image prune -f
+
+          # Show running containers
           docker ps
